import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,stat,readFile} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {openSubscriptions,DEFAULT_CATALOG} from '../src/subscriptions.mjs';
import {ACCOUNT_BINDINGS} from '../src/snapshot.mjs';
const DAY=86400000;

test('real settings DB preserves selections, imports atomically and retires stale official quotes',async t=>{
  const dir=await mkdtemp(join(tmpdir(),'qm-store-'));
  const original=JSON.parse(await readFile(DEFAULT_CATALOG,'utf8'));
  let now=Date.parse(original.revision)+DAY;
  let store=await openSubscriptions({dataDir:dir,now:()=>now});
  t.after(async()=>{store.close();await rm(dir,{recursive:true,force:true});});
  const snapshot={providers:[{id:'openai',accounts:[{id:'a'},{id:'b'}]}],[ACCOUNT_BINDINGS]:new Map([['openai\0a','a-id'],['openai\0b','b-id']])};
  const choose=planId=>store.select({provider:'openai',account:'a',planId,selectionContext:store.forAccount('openai','a','a-id').selectionContext},snapshot);
  assert.equal(store.forAccount('openai','a','a-id').monthlyUsd,null);
  assert.equal(choose('openai:plus').monthlyUsd,20);
  assert.equal(store.forAccount('openai','b','b-id').monthlyUsd,null);
  assert.equal((await stat(join(dir,'subscriptions.sqlite'))).mode&0o777,0o600);
  store.close();store=await openSubscriptions({dataDir:dir,now:()=>now});
  assert.equal(store.forAccount('openai','a','a-id').monthlyUsd,20);
  assert.equal(store.forAccount('openai','a','replacement').monthlyUsd,null);
  assert.equal(store.forAccount('openai','a','replacement').planId,null);
  const changed=structuredClone(original);changed.plans[0].monthlyUsd=1;
  assert.throws(()=>store.importCatalog(changed));
  assert.equal(store.forAccount('openai','a','a-id').monthlyUsd,20);
  const newer=structuredClone(original);newer.revision=new Date(now).toISOString();
  newer.plans.find(p=>p.id==='openai:plus').monthlyUsd=25;
  newer.plans.find(p=>p.id==='openai:plus').checkedAt=newer.revision;
  assert.equal(store.importCatalog(newer).status,'imported');
  assert.equal(store.importCatalog(original).status,'older-ignored');
  assert.equal(store.forAccount('openai','a','a-id').monthlyUsd,25);
  const downgrade=structuredClone(newer);now+=DAY;downgrade.revision=new Date(now).toISOString();downgrade.plans.find(p=>p.id==='openai:plus').checkedAt=original.revision;
  assert.throws(()=>store.importCatalog(downgrade));
  const invalid=structuredClone(newer);invalid.revision=new Date(now).toISOString();invalid.plans[1].monthlyUsd=-1;
  assert.throws(()=>store.importCatalog(invalid));
  assert.equal(store.forAccount('openai','a','a-id').monthlyUsd,25);
  assert.equal((await store.importFile(join(dir,'missing.json'))).status,'catalog-unavailable');
  assert.equal(store.forAccount('openai','a','a-id').monthlyUsd,25);
  now+=31*DAY;
  assert.equal(store.forAccount('openai','a','a-id').basis,'stale');
  assert.equal(store.forAccount('openai','a','a-id').monthlyUsd,null);
  assert.equal(store.forAccount('openai','a','a-id').lastQuotedUsd,25);
  const retired=structuredClone(newer);retired.revision=new Date(now).toISOString();retired.plans=retired.plans.filter(p=>p.id!=='openai:plus');store.importCatalog(retired);
  assert.equal(store.forAccount('openai','a','a-id').basis,'retired');
  assert.throws(()=>choose('openai:plus'),e=>e.status===422);
  assert.equal(choose(null).basis,'unselected');
  const publicList=store.list(snapshot);assert.equal(publicList.selections.length,0);
  assert.equal(publicList.plans.find(p=>p.id==='xai:supergrok-heavy').monthlyUsd,null);
  assert.ok(!JSON.stringify(publicList).includes('a-id'));
});

test('another SQLite connection sees imported catalog and preserves current selections',async t=>{
  const dir=await mkdtemp(join(tmpdir(),'qm-store-live-'));
  const catalog=JSON.parse(await readFile(DEFAULT_CATALOG,'utf8')),now=Date.parse(catalog.revision)+DAY;
  const reader=await openSubscriptions({dataDir:dir,now:()=>now}),writer=await openSubscriptions({dataDir:dir,now:()=>now});
  t.after(async()=>{reader.close();writer.close();await rm(dir,{recursive:true,force:true});});
  catalog.revision=new Date(now).toISOString();catalog.plans.find(p=>p.id==='openai:plus').monthlyUsd=30;
  writer.importCatalog(catalog);
  assert.equal(reader.list({providers:[]}).plans.find(p=>p.id==='openai:plus').monthlyUsd,30);
});
